# bisection.bisection.bisection { #root_finding.bisection.bisection.bisection }

```python
bisection.bisection.bisection(f, xmin, xmax, tol=1e-09, max_iter=500)
```

   Find roots of a scalar function using Bisection.

##    Parameters {.doc-section .doc-section----parameters}

   f : callable
       Function whose root is sought. Must accept a single scalar argument.
   xmin : float
       Lower bound of the initial interval.
   xmax : float
       Upper bound of the initial interval.
   tol : float, optional
       Absolute convergence tolerance for the bisection method.
       The method converges when |xmax - xmin| < `tol`.
       The default value is 1e-9.
    max_iter : int, optional
        maximum number of iterations allowable.
        Default is 500.

##    Returns {.doc-section .doc-section----returns}

   root : float
       The estimated root of the function `f`.

##     Raises {.doc-section .doc-section-----raises}

    ValueError
        If the initial interval [xmin, xmax] does not bracket the root
        (i.e., if f(xmin) and f(xmax) have the same sign).
    RuntimeError
        If the algorithm fails to converge within `max_iter` iterations.
    TypeError
        If the inputs are not of the expected types.

##    Notes {.doc-section .doc-section----notes}


   In general the bisection method requires that the root to be enclosed by the
   initial interval ``[xmin, xmax]``, i.e., ``f(xmin) * f(xmax) < 0``.
   It is used to produce an estimate that lies sufficiently close to
   the root when the relative convergence criteria ``tol`` is satisfied:

   Where ``| (xmax - xmin) | < tol``

`

##    Examples {.doc-section .doc-section----examples}

    >>> root = bisection(lambda x: 3*x**3 + 4*x**2 - 2*x - 2, 0, 2, max_iter = 500)
    >>> print(f"{root:.5f}")
        0.74827

