# bisection.bisection_find_roots.bisection_find_roots { #root_finding.bisection.bisection_find_roots.bisection_find_roots }

```python
bisection.bisection_find_roots.bisection_find_roots(
    f,
    xmin,
    xmax,
    tol=1e-06,
    max_iter=100,
    N=100,
)
```

   Find multiple roots of a scalar function using the bisection method.

   Split [xmin,xmax] into N-1 intervals and check for roots in each interval.

##    Parameters {.doc-section .doc-section----parameters}

   f : callable
       Function whose root is sought. Must accept a single scalar argument.
   xmin : float
       Lower bound of the initial interval.
   xmax : float
       Upper bound of the initial interval.
   tol : float, optional
       Absolute convergence tolerance for the bisection method.
       The method converges when |xmax - xmin| < `tol`.
       The default value is 1e-6.
    max_iter : int, optional
        maximum number of iterations allowable.
        Default is 100.
    N : int, optional
        Use to set number of intervals.
        Default is 100 (99 intervals).

##    Returns {.doc-section .doc-section----returns}

   roots : numpy array of floats
       The estimated roots of the function `f`.

##     Raises {.doc-section .doc-section-----raises}

    RuntimeError
        If the algorithm fails to converge within `max_iter` iterations.
    TypeError
        If the inputs are not of the expected types.

##    Notes {.doc-section .doc-section----notes}


   The bisection method requires that the root to be enclosed by the
   initial interval ``[xmin, xmax]``, i.e., ``f(xmin) * f(xmax) < 0``.
   It is used to produce an estimate that lies sufficiently close to
   the root when the relative convergence criteria ``tol`` is satisfied:

   Where ``| (xmax - xmin) | < tol``

   In general when searching for multiple root value the bisection method
   is NOT guaranteed to find roots, and is NOT guaranteed to find roots
   with multiplicity greater than 1 (e.g. roots of x**2)

   This function may return duplicate roots.
`

##    Examples {.doc-section .doc-section----examples}

    >>> roots = bisection_find_roots(lambda x: x**2 - 4, -3, 3, N=100)
    >>> print(roots)
        [-2.  2.]

    # Bisection method cannot find roots
    >>> roots = bisection_find_roots(lambda x: x**2 - 0.0001, -3, 3, tol=1e-9, max_iter = 1000, N=100)
    >>> print(roots)
        []

    # Smaller intervals now find roots
    >>> roots = bisection_find_roots(lambda x: x**2 - 0.0001, -3, 3, tol=1e-9, max_iter = 1000, N=1000)
    >>> print(roots)
        [-0.01  0.01]

    # Returns duplicate roots
    >>> roots = bisection_find_roots(lambda x: x**2 - 1, -3, 3, tol=1e-9, N=100)
    >>> print(roots)
        [-1. -1.  1.  1.]