# API Reference {.doc .doc-index}

## Bisection Method

Root finding using bisection method

| | |
| --- | --- |
| [bisection.bisection.bisection](bisection.bisection.bisection.qmd#root_finding.bisection.bisection.bisection) |    Find roots of a scalar function using Bisection. |
| [bisection.bisection_find_roots.bisection_find_roots](bisection.bisection_find_roots.bisection_find_roots.qmd#root_finding.bisection.bisection_find_roots.bisection_find_roots) |    Find multiple roots of a scalar function using the bisection method. |

## Newton's Method

Root finding using Newton-Raphson method

| | |
| --- | --- |
| [newton1d.newton1d](newton1d.newton1d.qmd#root_finding.newton1d.newton1d) | Find roots of a scalar function using Newton–Raphson. |

## Hybrid Method

Root finding using hybrid Bisection-Newton method

| | |
| --- | --- |
| [hybrid.hybrid](hybrid.hybrid.qmd#root_finding.hybrid.hybrid) | Find multiple roots of a scalar function using a hybrid |

## Visualization

Tools for plotting root finding results

| | |
| --- | --- |
| [plot_root.plot_root](plot_root.plot_root.qmd#root_finding.plot_root.plot_root) | Plot a scalar function and visualize its roots using a hybrid |